// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkctcAFtpBRCPKHerKHgq0gd6Mi46xze8',
    appId: '1:791355881093:web:6ccd538132d0c0e6e09bec',
    messagingSenderId: '791355881093',
    projectId: 'kift-tiktok-clone-v1',
    authDomain: 'kift-tiktok-clone-v1.firebaseapp.com',
    storageBucket: 'kift-tiktok-clone-v1.firebasestorage.app',
    measurementId: 'G-F725BRYYKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqR7Pjk5u1BsvUnV0rvTiGBpQWR5kUG0',
    appId: '1:791355881093:android:63e2547f0080d77ce09bec',
    messagingSenderId: '791355881093',
    projectId: 'kift-tiktok-clone-v1',
    storageBucket: 'kift-tiktok-clone-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCal-zUDU1LqRd6murUcvWasp1Isbt01wE',
    appId: '1:791355881093:ios:cad4048f0aa47fa8e09bec',
    messagingSenderId: '791355881093',
    projectId: 'kift-tiktok-clone-v1',
    storageBucket: 'kift-tiktok-clone-v1.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}